<?php

/**
 * Implementation of hook_menu() 
 */
function oneclick_client_menu() {
  
  $items['waiting'] = array(
    'page callback' => 'oneclick_client_is_waiting',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function oneclick_client_init() {
  //variable_set('site_waiting', TRUE); 
  //exit();
  if (variable_get('admin_waiting', FALSE) && !user_is_logged_in()) {

    variable_set('admin_waiting', FALSE);
    /*
    variable_set('root_site', 'openweb.in.th');

    drupal_http_request('http://'.variable_get('root_site', '').'/create_sitecon/'.variable_get('site_name', 'localhost').'?return=true');
    $_GET['return'] = 'true';
    oneclick_api_create_sitecon_client(variable_get('root_site', ''));

    $resp = drupal_http_request('http://'.variable_get('root_site', '').'/get_user_from_client/'.variable_get('site_name', 'localhost').'?format=json');

    $roles = user_roles();
    unset($roles[0]);
    $user = (array) json_decode($resp->data);
    $uid = db_query("SELECT uid FROM {users} WHERE name = :name", array(':name' => $user['name']))->fetchCol();
    if (empty($uid)) {
      $pass = $user['pass'];
      $user['roles'] = $roles;
      $user['status'] = 1;
      $user = user_save('', $user);
      db_update('users')
        ->fields(array('pass' => $pass))
        ->condition('uid', $user->uid)
        ->execute();
    }
    */
    drupal_goto('http://'.variable_get('root_site', '').'/sitecon/client/connect/'.variable_get('site_name', 'localhost').'/login', array('query' => array('redirect' => 'http://'.variable_get('site_name', 'localhost'))));
  }  
  
}

function oneclick_client_is_waiting() {
  print $_GET['callback'].'('.json_encode(array('waiting' => variable_get('site_waiting', TRUE))).')';
}


